### ISSUE TITLE
Can resnet prunning code work?

### ISSUE THREAD

**Issue by CloudHerods** [zzzxxxttt/pytorch_AMC#1]
hi, thanks to your great work that i learned very much. there's a little problem when i run the cifar_search.py using the resnet, but plain20 work. 
Do you have same issue?

**Comment by zzzxxxttt** [comment]
Could you paste the error message? It will be useful to identify the problem.

**Comment by CloudHerods** [comment]
layers.6.skip_bn.running_mean not in pretrained dict !
layers.6.skip_bn.running_var not in pretrained dict !
layers.6.skip_bn.num_batches_tracked not in pretrained dict !
Traceback (most recent call last):
  File "cifar_search.py", line 153, in <module>
    main()
  File "cifar_search.py", line 97, in main
    state, _, done, _ = learner.init_episode()
  File "/home/Brin1/pytorch_AMC-master/learners/channel_pruning.py", line 169, in init_episode
    self.model.load_state_dict(model_dict)
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PreActResNet:
        size mismatch for layers.3.mask0: copying a param with shape torch.Size([1, 16, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 32, 1, 1]).
        size mismatch for layers.3.mask1: copying a param with shape torch.Size([1, 16, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 32, 1, 1]).
        size mismatch for layers.3.conv0.weight: copying a param with shape torch.Size([16, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 16, 3, 3]).

**Comment by CloudHerods** [comment]
Traceback (most recent call last):
  File "cifar_search.py", line 153, in <module>
    main()
  File "cifar_search.py", line 100, in main
    next_state, real_action, done, score = learner.compress(action)
  File "/home/Brin1/pytorch_AMC-master/learners/channel_pruning.py", line 251, in compress
    self.model.apply_layer_mask(keep_inds, layer_name=layer_now)
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'PreActResNet' object has no attribute 'apply_layer_mask'
--------------------------------------------------------------------------------
I add one return(int(real_a)) in the compress.py of 'cifar_resnet_proxy.py'

**Comment by zzzxxxttt** [comment]
Oh I fogot to rename the functions. The function "apply_1layer_mask" and "apply_1layer_weight" in PreActResNet should be renamed to "apply_layer_mask" and "apply_layer_weight", respectively.

**Comment by CloudHerods** [comment]
> Oh I fogot to rename the functions. The function "apply_1layer_mask" and "apply_1layer_weight" in PreActResNet should be renamed to "apply_layer_mask" and "apply_layer_weight", respectively.
------------------------
thank you very much! 
i'm trying to apply dense conv operation without using mask, because the mask can not speedup when model finetuning or inference. Do you wanna deal with the issue?
I would appreciate if i can add in your wechat to talk about AMC and other algorithms !

**Comment by zzzxxxttt** [comment]
Currently I don't have time to implement the conv pruning, but I think it is trivial to implement such stuff.
You can contact me via email zxt1993@mail.ustc.edu.cn.
